"""columna created_at añadidas

Revision ID: c79bc86862e1
Revises: 
Create Date: 2026-01-05 00:18:17.561711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = 'c79bc86862e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbtools$execution_history')
    op.add_column('todos', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('todos', 'created_at')
    op.create_table('dbtools$execution_history',
    sa.Column('id', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('hash', sa.CLOB(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_on', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_on', oracle.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('statement', sa.CLOB(), nullable=True),
    sa.Column('times', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dbtools$execution_history_pk')),
    oracle_tablespace='DATA'
    )
    # ### end Alembic commands ###
